# Generated by Django 5.0.6 on 2024-06-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoesvareity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
